version: '3.8'
services:
  # Wordpress
  php-app:
    build:
      # Build Dockerfile context on the current directory
      context: .
      dockerfile: Dockerfile 
    volumes:
      # local ./src directory contains PHP code
      # Mount it to the to /var/www/html on the container
      - ./src:/var/www/html
    depends_on:
      # Ensure MySQL is started before PHP
      - mysql
    ports:
      # Let Apache Expose PHP to the web on 3000
      - 3000:80

  # MySQL Database
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin
    links:
      - mysql
    ports:
      - 3001:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 512M


